### ISSUE TITLE
Radio Board revA Hardware schematic RFC

### ISSUE THREAD

**Issue by ATGr8** [USSTR-Avionics/Mumbai#1]
Need two Passes to move onto layout as discussed in the design review. 
Design files: https://github.com/USSTR-Avionics/Mumbai/tree/master/RF
Let me know if you have further questions

**Comment by tyrelkostyk** [comment]
Approved.

Since the majority of these changes are utilizing a somewhat proven open source design, there's not too much to comment on. Be sure to thoroughly test the added components (external memory), and consider investigating what other people have done when making modifications to the firmware/hardware for this design. There will definitely be some trial-and-error when using that external memory, but it shouldn't be too hard. Let me know if you experience significant issues and I can try and lend a hand.

**Comment by Colton-Breitkreuz** [comment]
Approved.
