### ISSUE TITLE
RFC 202305020937: Impl continuous fuzzing

### ISSUE THREAD

**Issue by frroossst** [USSTR-Avionics/Mumbai#7]
# Abstract
Fuzz testing find bugs, faster, better, and with less effort than writing regular tests, allowing us to focus more of our time on writing code, architecture rather than correctness of the code. This was an active RFC on `USSTR-Avionics/MiniRocket`  but it was too late in its life cycle to do this. Ideally, this would be handled by a github action automatically to find and report bugs. Or it can live on the Esterhazy server. 

# Problem(s)
Program robustness, memory safety, correctness, undefined behaviour.

# Solution
Use clang's libfuzz, or write our own fuzz library

# Difficulties and Risks
Even after months of looking into it, I still have very little idea on how to write my own fuzzer. 

# Estimated costs and timelines
Should write our own fuzzer in about a month or so, with all the features we want, or impl a fuzzer in a week or so. Saves a lot of cost in the long term.

# Proof of concept
Haven't implemented one yet

# References
https://owasp.org/www-community/Fuzzing
https://releases.llvm.org/9.0.0/docs/LibFuzzer.html
https://www.code-intelligence.com/blog/secure-coding-cpp-using-fuzzing
https://github.com/google/honggfuzz
https://github.com/CodeIntelligenceTesting/cifuzz

**Comment by frroossst** [comment]
This is a complex topic that requires in depth discussions, so I will leave this open for two weeks.

/remind fuzz test RFC in 2 weeks

**Comment by dhaussecker** [comment]
Prime example of: “Research done on student rocket projects shows that time and time again, students tend to overcomplicate certain aspects, rather than focusing on the simplest solution that can be effective.”

This is a clear example of this in my opinion, please focus on the simple stuff of implementing all the boards we already have planned and the software for those as that is the simplest thing we can do at this point

**Comment by dhaussecker** [comment]
Just because it sounds cool doesn’t mean it is something we need at this point. Reminder: 4 month timeline for all boards and code to be done. Best case scenario this would get done in 2 months,

**Comment by frroossst** [comment]
- What research? Source?
- The reasoning is mentioned in the RFC, nowhere is the word "cool" mentioned
- What is your basis for arriving at the conclusion that implementing continuous fuzzing would take 2 months? I LITERALLY linked a reference to a fuzzing library for C++, that you can use right  now
- This in the long term ensures more robust and secure embedded code is written, it **might be** worthwhile to at least have a discussion on it to prevent bugs like the FRAM bug we had!

**Comment by dhaussecker** [comment]
- Multiple papers from student project cite this as the most significant issue faced in student projects. For example: https://www.hyrumwright.org/papers/avionics.pdf
- The goal with everything we are doing is asking one simple question: is it absolutely essential for a rocket? Meaning it helps us meet one of the 3 requirements required for avionics (command, control, data acquisition). Remember timelines are quick, we only have a few hours a week committed at this point, any time we can get to make sure our rocket simply works is time we need
- “Should write our own fuzzer in about a month or so”, multiply that timeline by 2 since it will ALWAYS take longer than you think and you get 2 months. If it takes a couple of hours for you to implement an already made library, and develop some documentation on how it works/ how to use it / why is it useful, then I’m for it. But I need to see a valid justification that it will only take a few hours

**Comment by frroossst** [comment]
- I haven't dived into the paper yet, but I'll take your word for it now
- It helps the rocket be safe? Since, there is no RTOS, a bug or crash is catastrophic as your engine task stops being executed? What happens on a seg fault? What happens if enough memory can't be allocated? What happens when static variables are mutated improperly? All these operations are inherently even more so an an embedded system
- We should write our own fuzzer eventually, but the goal should be to implement fuzzing in the first place, the crux of the RFC is fuzzing not, implementation of fuzzing. I'm open to any fuzzing lib as long as it serves its purpose and fulfills our needs

**Comment by ATGr8** [comment]
Is there a fuzzer that already exists that we can just use? 
I like this idea but I don't wanna take away too much time from writing Mumbai software/firmware, could still be convinced that writing our own fuzzer is better for long term but I don't understand it enough to appreciate it.

**Comment by frroossst** [comment]
[A gentle introduction to fuzzing C++ code](https://jefftrull.github.io/c++/clang/llvm/fuzzing/sanitizer/2015/11/27/fuzzing-with-sanitizers.html)

I have been saying this for a long time, "If you are smart enough to write tests that catch all the bugs that might arise, aren't you smart enough to write code, without those bugs?" that's why Test Driven Development doesn't work unless you are building something hyper-testable most likely a CLI utililty or a parser. 

Writing system tests for a system means emulating the environment around it, which is ridiculously difficult. So, fuzzing just means, you are rawdogging you functions with inputs of all kinds such that you find the bug easily. This is what I've been calling "chaotic testing" for a long time,, just write code, and test it as a full system, something crashes go back and fix. 

At work, we've found some very nasty RegEx bugs by just fuzzing. But we all know you should never use RegEx, so that's our bad I guess haha

**Comment by frroossst** [comment]
NOTE: This should be opened up on `USSTR-Avionics/Achilles` the next time.
